### ISSUE TITLE
Heredoc specification typo

### ISSUE THREAD

**Issue by valich** [puppetlabs/puppet-specifications#21]
Hello there,

The example in <https://github.com/puppetlabs/puppet-specifications/blob/master/language/heredoc.md#splitting-and-joining-long-lines> opens heredoc as `@(END:L)`. I wonder if it should have been `@(END/L)` for escaping newlines, not syntax checking for ‘L’ language?

Thank you.

**Comment by hlindberg** [comment]
Yes, that is a typo, fixing. Thanks for reporting
