### ISSUE TITLE
Missing definition of QualifiedReference

### ISSUE THREAD

**Issue by DavidS** [puppetlabs/puppet-specifications#76]
The term `QualifiedReference` is used at multiple places in the grammar, but I could not find its formal definition. Please help.

**Comment by hlindberg** [comment]
It is defined in the "lexical_structure.md" document. Title: "Upper Case Bare Words / REF / Qualified Reference"

**Comment by hlindberg** [comment]
I made a change, the text sas "Qualified Resource", which made it hard to search for. Removed the space so it now reads "QualifiedReference"
